SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H inner join CAR_RENTAL_COMPANY_CAR C
                                                    ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단' and month(H.START_DATE) = 10
ORDER BY C.CAR_ID desc;

## exist를 사용하는 방법
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
WHERE C.CAR_TYPE = '세단'
  AND EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID
      AND MONTH(H.START_DATE) = 10
)
ORDER BY C.CAR_ID DESC;
