SELECT
    YEAR_DATA.YEAR,
    (YEAR_DATA.MAX_SIZE - D.SIZE_OF_COLONY) YEAR_DEV,
    D.ID
FROM ECOLI_DATA D inner join
     (
         SELECT
             YEAR(D.DIFFERENTIATION_DATE) YEAR,
             MAX(D.SIZE_OF_COLONY) MAX_SIZE
         FROM ECOLI_DATA D
         GROUP BY YEAR(D.DIFFERENTIATION_DATE)
     )  YEAR_DATA
     ON YEAR(D.DIFFERENTIATION_DATE) = YEAR_DATA.YEAR
ORDER BY YEAR_DATA.YEAR, YEAR_DEV