SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A inner join FISH_NAME_INFO B
                            ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, A.LENGTH) IN (
    SELECT FISH_TYPE, MAX(IFNULL(LENGTH,10))
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY A.ID

# GROUP BY를 쓸 경우 SELECT 절에는 해당 GROUP BY의 속성이나 집계함수만 사용이 가능