SELECT F.PRODUCT_ID, F.PRODUCT_NAME, SUM(O.TOTAL_SALES) TOTAL_SALES
FROM FOOD_PRODUCT F inner join (
    SELECT P.PRODUCT_ID, SUM(P.PRICE * K.AMOUNT)  TOTAL_SALES
    FROM FOOD_PRODUCT P inner JOIN FOOD_ORDER K ON P.PRODUCT_ID = K.PRODUCT_ID
    WHERE date_format(K.PRODUCE_DATE, "%Y-%m") = '2022-05'
    GROUP BY P.PRODUCT_ID
) O ON F.PRODUCT_ID = O.PRODUCT_ID
GROUP BY F.PRODUCT_ID
ORDER BY TOTAL_SALES desc,  F.PRODUCT_ID