SELECT A.ANIMAL_ID,	A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A inner join ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE like "%Intact%" and
      (B.SEX_UPON_OUTCOME like "%Spayed%" or B.SEX_UPON_OUTCOME like "%Neutered%")