SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(D.REVIEW_SCORE),2) SCORE
FROM REST_INFO I inner join REST_REVIEW D on I.REST_ID = D.REST_ID
WHERE I.ADDRESS like '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE desc, FAVORITES desc

# REST_ID는 고유하므로 GROUP BY id를 할 경우 나머지가 같은 값이 나온다 그래서 따로 조인할 필요가 없다.