SELECT B.USER_ID, B.NICKNAME, sum(A.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD A inner join USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES