SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID not in (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
order by ITEM_ID desc;

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL AND ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC;