SELECT MONTH(A.START_DATE) MONTH, A.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE month(A.START_DATE) between '08' and '10'
  and A.CAR_ID in (
    SELECT B.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE month(B.START_DATE) between '08' and '10'
    GROUP BY B.CAR_ID
    HAVING COUNT(B.CAR_ID) >= 5
    )
GROUP BY MONTH, CAR_ID
ORDER BY MONTH asc, A.CAR_ID desc;