SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM (
         SELECT *
         FROM REST_INFO
         GROUP BY FOOD_TYPE, FAVORITES
         ORDER BY FAVORITES desc
     ) A
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE desc;

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY 1 DESC;