SELECT G.SCORE,	E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E inner join (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) G ON E.EMP_NO = G.EMP_NO
ORDER BY G.SCORE DESC
limit 1;

# MAX로 푸는 방법
SELECT G.SCORE,	E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E inner join (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) G ON E.EMP_NO = G.EMP_NO
WHERE G.SCORE = (
    SELECT MAX(SUM_SCORE)
    FROM (
             SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
             FROM HR_GRADE
             GROUP BY EMP_NO
     )T
);