SELECT year(O.SALES_DATE) YEAR, month(O.SALES_DATE) MONTH, U.GENDER, count(distinct(U.USER_ID)) USERS
FROM USER_INFO U inner join ONLINE_SALE O on U.USER_ID = O.USER_ID
WHERE U.GENDER is not NULL
GROUP BY year(O.SALES_DATE), month(O.SALES_DATE), U.GENDER
ORDER BY YEAR, MONTH, GENDER