SELECT A.AUTHOR_ID, A.AUTHOR_NAME, D.CATEGORY, SUM(D.TOTAL_SALES) TOTAL_SALES
FROM AUTHOR A inner join (
    SELECT B.AUTHOR_ID, B.CATEGORY, (B.PRICE * S.SALES) TOTAL_SALES
    FROM BOOK B inner JOIN BOOK_SALES S on B.BOOK_ID = S.BOOK_ID
    WHERE date_format(S.SALES_DATE, '%Y-%m') = '2022-01'
) D on A.AUTHOR_ID = D.AUTHOR_ID
GROUP BY A.AUTHOR_ID, D.CATEGORY
ORDER BY A.AUTHOR_ID, D.CATEGORY desc;